ISSUE_TYPES = [
    "POTHOLE", "ROAD_CRACK", "WATERLOGGING", "BROKEN_FOOTPATH",
    "DAMAGED_MANHOLE", "DAMAGED_SIGN", "BROKEN_STREETLIGHT", "OTHER",
]
SEVERITIES = ["LOW", "MEDIUM", "HIGH", "CRITICAL"]
SEV_RANK = {s: i for i, s in enumerate(SEVERITIES)}

ROLES = ["CITIZEN", "MUNICIPAL_MEMBER", "ADMIN"]

STATUSES = [
    "NEW", "VERIFIED", "ASSIGNED", "IN_PROGRESS", "COMPLETED",
    "AWAITING_VERIFICATION", "REQUIRES_REVIEW", "RESOLVED",
]
OPEN_STATUSES = [s for s in STATUSES if s != "RESOLVED"]

MEDIA_ROLES = ["CITIZEN_REPORT", "REPAIR_BEFORE", "REPAIR_DURING", "REPAIR_AFTER", "OTHER"]
PRIORITY_LEVELS = ["LOW", "MEDIUM", "HIGH", "CRITICAL"]
